on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read tagSpec.yml to get Tag version type
        id: custom-tag
        run: |
          TAG=`cat tagSpec.yml | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs`
          echo "::set-output name=tag::$(echo $TAG)"
        shell: bash
      - name: Bump version and push tag
        id: tag_version
        uses: vishalrastogi13/tag-update-action-copy@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.custom-tag.outputs.tag }}

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.custom-tag.outputs.tag }}
          release_name: Release ${{ steps.custom-tag.outputs.tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false